### PR TITLE
Fix Swift 2.2 deprecation warnings

### PR DESCRIPTION
**Pull request by argon**

### CODE REVIEW

**Comment by bahlo** [comment]
Thank you for the PR, it'll take part in the next release :ok_hand: :tada:

**Comment by argon** [comment]
Any idea when that might be? My CI logs are unreadable due to all the deprecation warnings.

**Comment by bahlo** [comment]
I'm sorry for your inconvenience. I've created the bugfix release [`v1.5.3`](https://github.com/bahlo/SwiftGif/releases/tag/v1.5.2), which contains your changes. 

Thanks for using SwiftGif :+1:

**Comment by argon** [comment]
Thanks @bahlo, I appreciate it!

**Pull request merged**
