### PR TITLE
add UIImageView extension for GCD

### PR DESCRIPTION
**Pull request by WXGBridgeQ**
haven't test more, but I think this should improve the performance

### CODE REVIEW

**Comment by WXGBridgeQ** [comment]
a little problem, a delay with no display when calculate the frames, maybe add the first frame as the placeholder is a good idea

**Comment by bahlo** [comment]
Thanks for the PR! I'll look into it in the next days :+1:

**Comment by bahlo** [comment]
What you said about adding the first frame is a good idea - would you mind adding that as well?

**Comment by WXGBridgeQ** [comment]
Sorry, don't have time to do this now, I'm on my vacation, will work after the Chinese New Year.

**Comment by bahlo** [comment]
Alright, have a great vacation! :ok_hand::palm_tree:

**Comment by bahlo** [comment]
Merged in [v1.6-beta.1](https://github.com/bahlo/SwiftGif/releases/tag/v1.6-beta.1) (soon to be master) awesome PR 💯

**Pull request closed without merging**
