### PR TITLE
Made calling SwiftGif Easier

### PR DESCRIPTION
**Pull request by goktugyil**
Now you can call SwiftGif only by knowing the gif files name:
UIImage.gifWithName("jeremy")

or can call the old method if prefered:
UIImage.gifWithData(imageData!)

### CODE REVIEW

**Comment by bahlo** [comment]
Thanks for the PR, appreciate it :+1: 

Is there a reason you removed the `public` statements before the methods?

**Comment by goktugyil** [comment]
No, just wasn't paying attention cause it compiled. Are there cases where public keyword is essential?

**Comment by bahlo** [comment]
See [Access Levels](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/Swift_Programming_Language/AccessControl.html#//apple_ref/doc/uid/TP40014097-CH41-ID5) :blush:

**Comment by bahlo** [comment]
It would be great if you could add the `public` statements. The rest looks really good! :+1:

**Comment by goktugyil** [comment]
done

**Comment by bahlo** [comment]
Merged in [`1.5`](https://github.com/bahlo/SwiftGif/releases/tag/v1.5). Thank you!

**Pull request closed without merging**
