### PR TITLE
Check if `gifProperties` is 0x0 object

### PR DESCRIPTION
**Pull request by m4rr**

### CODE REVIEW

**Comment by m4rr** [comment]
It's better to throw an exception for this case. Because it's probably not-a-gif with `.gif` extension. But this change will prevent a crash.

**Comment by bahlo** [comment]
Thank you for the PR! I'm so sorry this took so long. Will merge this weekend hopefully

**Comment by bahlo** [comment]
Can you check if this is still necessary in [v1.6-beta.1](https://github.com/bahlo/SwiftGif/releases/tag/v1.6-beta.1)? Please reopen if yes 😁

**Comment by m4rr** [comment]
Ok, I'll check it. But this would take some time.

**Pull request closed without merging**
